# Generated by Django 3.2.10 on 2022-01-12 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_alter_drop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
