# Generated by Django 3.2.10 on 2022-01-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_drop_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
