# Generated by Django 3.2.10 on 2022-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0006_drop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drop',
            name='futurefavourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drop',
            name='genre',
            field=models.CharField(blank=True, default='No genre', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='mostanticipated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drop',
            name='releasedateandtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
