# Generated by Django 3.2.10 on 2022-02-07 02:05

from django.db import migrations, models
import drops.models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0007_auto_20220206_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=drops.models.collection_image_upload_handler),
        ),
    ]
