# Generated by Django 3.2.10 on 2022-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0008_drop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='genre',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
