# Generated by Django 3.2.10 on 2022-03-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0009_alter_drop_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
