# Generated by Django 3.2.10 on 2022-03-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0012_rename_releasedateandtime_drop_release_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='release_date_and_time',
        ),
        migrations.AddField(
            model_name='drop',
            name='release_date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='drop',
            name='release_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
