# Generated by Django 3.2.10 on 2022-03-22 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ncollections', '0003_ncollection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncollection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ncollection',
            name='sociallinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncollection',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ncollection',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=220),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ncollection',
            name='weeklyvolume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
