# Generated by Django 3.2.10 on 2022-03-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncollections', '0007_alter_ncollection_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnft',
            name='attributes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nnft',
            name='linktobuy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nnft',
            name='rarity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nnft',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
