# Generated by Django 3.2.10 on 2022-03-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncollections', '0008_auto_20220322_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nnft',
            old_name='linktobuy',
            new_name='link_to_buy',
        ),
    ]
