# Generated by Django 3.2.10 on 2022-03-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncollections', '0009_rename_linktobuy_nnft_link_to_buy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ncollection',
            old_name='sociallinks',
            new_name='social_links',
        ),
        migrations.RenameField(
            model_name='ncollection',
            old_name='weeklyvolume',
            new_name='weekly_volume',
        ),
    ]
