# Generated by Django 3.2.10 on 2022-03-27 02:19

from django.db import migrations, models
import ncollections.models


class Migration(migrations.Migration):

    dependencies = [
        ('ncollections', '0011_auto_20220327_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncollection',
            name='image',
            field=models.ImageField(null=True, upload_to=ncollections.models.collection_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='nnft',
            name='image',
            field=models.ImageField(null=True, upload_to=ncollections.models.nft_image_upload_handler),
        ),
    ]
