# Generated by Django 3.2.10 on 2022-01-22 01:01

from django.db import migrations, models
import django.db.models.deletion
import nftcollections.models


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=nftcollections.models.nft_image_upload_handler)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nftcollections.nftcollection')),
            ],
        ),
    ]
