# Generated by Django 3.2.10 on 2022-01-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0002_nftimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftimage',
            old_name='recipe',
            new_name='nftcollection',
        ),
    ]
