# Generated by Django 3.2.10 on 2022-02-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0003_rename_recipe_nftimage_nftcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftcollection',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
