# Generated by Django 3.2.10 on 2022-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0004_nftcollection_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='linktobuy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='sociallinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nftcollection',
            name='weeklyvolume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
