# Generated by Django 3.2.10 on 2022-02-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0009_alter_nftcollection_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftcollection',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
