# Generated by Django 3.2.10 on 2022-02-09 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftcollections', '0010_alter_nftcollection_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=220)),
                ('name', models.CharField(max_length=220)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nftcollections.nft')),
            ],
        ),
        migrations.DeleteModel(
            name='NftImage',
        ),
    ]
